export const LISTAR_PRODUTOS = 'LISTAR_PRODUTOS';
export const ADICIONAR_PRODUTO = 'ADICIONAR_PRODUTO';
export const EDITAR_PRODUTO = 'EDITAR_PRODUTO';
export const EXCLUIR_PRODUTO = 'EXCLUIR_PRODUTO';
export const NOVO_PRODUTO = 'NOVO_PRODUTO';